apiVersion: v1
kind: Pod
metadata:
  name: readinesspod-test
  labels:
    app: readinesspod-test
spec:
  containers:
    - name: readinesspod-test
      image: nginx:1.19.1
      imagePullPolicy: IfNotPresent
      readinessProbe: # 就绪探针
        httpGet:
          port: 80
          path: /index1.html
        initialDelaySeconds: 2 #初始化时间
        periodSeconds: 3 #重新检查时间
  restartPolicy: Always
