apiVersion: v1
kind: Pod
metadata:
  name: livenessprobe3-test
  labels:
    app: livenessprobe3-test
spec:
  containers:
    - name: livenessprobe3-test
      image: nginx:1.19.1
      imagePullPolicy: IfNotPresent
      ports:
        - name: nginx-http-get
          containerPort: 80
      livenessProbe:
        tcpSocket:
          port: 8080
        initialDelaySeconds: 1
        periodSeconds: 3
        timeoutSeconds: 10
  restartPolicy: Always