apiVersion: v1
kind: Pod
metadata:
  name: lifecycle-test
  labels:
    app: lifecycle-test
spec:
  containers:
    - name: lifecycle-test
      image: busybox:1.32.0
      imagePullPolicy: IfNotPresent
      command: ['sh','-c','sleep 5000']
      lifecycle:
        postStart:
          exec:
            # 创建/data/k8s目录，在目录下创建index.html
            command: ['mkdir','-p','/data/k8s/index.html']
  restartPolicy: Always