apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mariadb-sts
  labels:
    app: mariadb-sts
spec:
  replicas: 1
  serviceName: mariadb-svc
  template:
    metadata:
      name: mariadb-sts
      labels:
        app: mariadb-sts
    spec:
      imagePullSecrets:
        - name: harbor-59.3 # 注册私服
      containers:
        - name: mariadb-sts
          image: 192.168.59.3:5000/public/mariadb:10.5.2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              #这是mysqlroot用户的密码
              valueFrom:
                secretKeyRef:
                  key: password
                  name: mariadb-secret
            - name: TZ
              value: Asia/Shanghai
            # 创建数据库
            - name: MYSQL_DATABASE
              value: test
          args:
            - "--character-set-server=utf8mb4"
            - "--collation-server=utf8mb4_unicode_ci"
          volumeMounts:
            - name: mariadb-conf #随便给一个名字,这个名字必须与volumes.name一致
              mountPath: /etc/mysql/mariadb.conf.d/   #容器内的挂载目录
            - name: mariadb-data
              mountPath: /var/lib/mysql
      restartPolicy: Always
      volumes:
        - name: mariadb-data
          persistentVolumeClaim:
            claimName: mariadb-pvc
        - name: mariadb-conf
          configMap:
            name: mariadb-configmap
  selector:
    matchLabels:
      app: mariadb-sts
---
apiVersion: v1
kind: Service
metadata:
  name: mariadb-svc
spec:
  selector:
    app: mariadb-sts
  ports:
    - port: 8080
  clusterIP: None