apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb-deploy
  labels:
    app: mariadb-deploy
spec:
  replicas: 1
  template:
    metadata:
      name: mariadb-deploy
      labels:
        app: mariadb-deploy
    spec:
#      nodeSelector: 根据标签指定节点
#        mariadb: mariadb
#      nodeName: k8s-node02
      imagePullSecrets:
        - name: harbor-59.3
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution: # 硬亲和性
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - k8s-node02
          preferredDuringSchedulingIgnoredDuringExecution: # 软亲和性
            - preference:
                matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - k8s-node02
              weight: 20
      containers:
        - name: mariadb-deploy
          image: 192.168.59.3:5000/public/mariadb:10.5.2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3307
          env:
            - name: MYSQL_ROOT_PASSWORD
              #这是mysqlroot用户的密码
              valueFrom:
                secretKeyRef:
                  key: password
                  name: mariadbsecret
            - name: TZ
              value: Asia/Shanghai
          args:
            - "--character-set-server=utf8mb4"
            - "--collation-server=utf8mb4_unicode_ci"
          volumeMounts:
            - mountPath: /etc/mysql/mariadb.conf.d/   #容器内的挂载目录
              name: mariadb-conf #随便给一个名字,这个名字必须与volumes.name一致
      restartPolicy: Always
      volumes:
        - name: mariadb-conf
          configMap:
            name: mariadb-configmap
  selector:
    matchLabels:
      app: mariadb-deploy
---
apiVersion: v1
kind: Service
metadata:
  name: mariadb-svc
spec:
  selector:
    app: mariadb-deploy
  ports:
    - port: 3307
      targetPort: 3307
      nodePort: 30036
  type: NodePort