apiVersion: batch/v1
kind: Job # or CronJob 周期任务
metadata:
  name: jobdemo
  labels:
    app: jobdemo
spec:
  template:
    spec:
      containers:
        - name: jobdemo
          image: perl:slim
          imagePullPolicy: IfNotPresent
          command: ["perl",  "-Mbignum=bpi", "-wle", "print bpi(2000)"]
      restartPolicy: Never
  backoffLimit: 4